image: publysher/hugo

pages:
  script:
  - hugo
  - npm install firebase-tools
  - firebase use --token $FIREBASE_DEPLOY_KEY alias
  - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  artifacts:
    paths:
    - public
  only:
  - master

