title                  = "Javi Pulido's blog"
author                 = "Javi Pulido"
baseUrl                = "https://javipulido.com"
theme                  = "hugo-theme-pixyll-minimal"

archetypeDir           = "archetypes"
contentDir             = "content"
themesDir              = "themes"
layoutDir              = "layouts"
publishDir             = "public"

languageCode           = "en"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
enableEmoji            = true
DefaultContentLanguage = "en"

#disqusShortname        = ""

[Languages]
[Languages.en]
weight = 1

#[Languages.es]
#weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  google_analytics_id = "UA-27524292-4"
  twitter_username = "pulimento"
  paginate = 3