archetypeDir           = "archetypes"
author                 = "Javi Pulido"
baseUrl                = "https://mybeautifulfreeblog.firebaseapp.com"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
contentDir             = "content"
languageCode           = "en-us"
layoutDir              = "layouts"
publishDir             = "public"
theme                  = "hugo-theme-pixyll-minimal"
themesDir              = "themes"
title                  = "Javi Pulido's blog"
enableEmoji            = true
DefaultContentLanguage = "en"
#disqusShortname        = ""

[Languages]
[Languages.en]
weight = 1

[Languages.es]
weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

[indexes]
  category = "categories"
  tag = "tags"

[params]
  google_analytics_id = "UA-27524292-4"
  twitter_username = "pulimento"
  paginate = 3