title = "Pulimento's blog"
author = "adminauthor"
theme = "hugo-theme-pixyll"
languageCode = "es-es"

baseurl = "https://mybeautifulfreeblog.firebaseapp.com"

#####

contentdir = "content"
publishdir = "public"
archetypeDir = "archetypes"
layoutDir = "layouts"
builddrafts = false
enableEmoji = true
DefaultContentLanguage = "es"

[indexes]
  category = "categories"
  tag = "tags"

# Enable comments by entering your Disqus shortname
#disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  #title = "Hey Pulimento"
  #subtitle = "a minimal theme for ~~Ghost~~ Hugo"
  copyright = "Released under the MITTTTT license."

  # You can choose between green, orange, red and blue.
  #themecolor = "green"

  # Link custom assets relative to /static
  favicon   = "favicon.ico"
  customCSS = []
  customJS  = []

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name = "John Doe"
  bio = "programmer - blogger - coffee aficionado"
  description = "Your description of the blog"
  
  # Link your social networks (optional)
  #location = ""
  #twitter = "spf13"
  #linkedin = ""
  #googleplus = ""
  #facebook = ""
  #instagram = ""
  #github = "spf13"
  #gitlab = ""
  #bitbucket = ""

  search_engine = true
  #google_analytics_id = ""
  twitter_username = "pulimento"
  paginate = true

  # Customize or translate the strings
  #keepReadingStr = "Keep reading"
  #backtotopStr = "Back to top"
  #shareStr = "Share"
  #pageNotFoundTitle = "404 - Page not found"