title                  = "Javi Pulido's blog"
author                 = "Javi Pulido"
baseUrl                = "https://javipulido.com"
theme                  = "hugo-theme-pixyll-minimal"
pygmentsCodefences     = true
pygmentsStyle          = "pygments"

[permalinks]
  post = "/:filename/"

archetypeDir           = "archetypes"
contentDir             = "content"
themesDir              = "themes"
layoutDir              = "layouts"
publishDir             = "public"

languageCode           = "en"
buildDrafts            = false
relativeURLs           = true
canonifyUrls           = true
enableEmoji            = true
DefaultContentLanguage = "en"
enableRobotsTXT        = true

paginatePath           = "page"
pygmentsCodeFencesGuessSyntax  = true


[params]
  twitter_username = "pulimento"
  google_analytics_id = "UA-27524292-4"
  paginate = 5

[Languages]
[Languages.en]
weight = 1

#[Languages.es]
#weight = 2

[blackfriday]
angledQuotes = true
hrefTargetBlank = true

# remove all taxonomies, except tags
[taxonomies]
  tag = "tags"
