on: [push]
name: Publish blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the hugo container
      uses: actions/hugo-action@master
