on: [push]
name: Publish blog
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: pulimento/hugo-action@master
      with:
        firebase-token: ${{ secrets.secret_firebase_token }}
